/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ll.pkg1;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author huqingyu18
 */
public class LL1Frame extends javax.swing.JFrame {

    /**
     * Creates new form LL1Frame
     */
    public LL1Frame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        filePath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileContent = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        eliminateLeft = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        extractLeft = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saveEliminate = new javax.swing.JButton();
        saveExtract = new javax.swing.JButton();
        saveRules = new javax.swing.JButton();
        execute = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tablePanel = new javax.swing.JScrollPane();
        judgeLabel = new javax.swing.JLabel();
        judgeResult = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        anaStackResult = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        anaStrResult = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        anaResultResult = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        waitStr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LL(1)分析器");
        setResizable(false);

        jPanel1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel2.setText("文本路径：");

        filePath.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jButton1.setText("浏览");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        fileContent.setColumns(20);
        fileContent.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        fileContent.setRows(5);
        jScrollPane2.setViewportView(fileContent);

        jButton2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jButton2.setText("帮助");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        eliminateLeft.setColumns(20);
        eliminateLeft.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        eliminateLeft.setRows(5);
        jScrollPane1.setViewportView(eliminateLeft);

        extractLeft.setColumns(20);
        extractLeft.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        extractLeft.setRows(5);
        jScrollPane3.setViewportView(extractLeft);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel1.setText("消除左递归后的文法规则");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel3.setText("提取公因子后的文法规则");

        saveEliminate.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        saveEliminate.setText("保存");
        saveEliminate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEliminateActionPerformed(evt);
            }
        });

        saveExtract.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        saveExtract.setText("保存");
        saveExtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveExtractActionPerformed(evt);
            }
        });

        saveRules.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        saveRules.setText("保存");
        saveRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRulesActionPerformed(evt);
            }
        });

        execute.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        execute.setText("执行");
        execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel4.setText("LL(1)分析表");

        tablePanel.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N

        judgeLabel.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        judgeLabel.setText("LL(1)文法判断结果：");

        judgeResult.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        judgeResult.setText("待判断");

        anaStackResult.setColumns(20);
        anaStackResult.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        anaStackResult.setRows(5);
        jScrollPane4.setViewportView(anaStackResult);

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel5.setText("分析栈的变化情况");

        anaStrResult.setColumns(20);
        anaStrResult.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        anaStrResult.setRows(5);
        jScrollPane5.setViewportView(anaStrResult);

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel6.setText("需要分析的句子的变化情况");

        anaResultResult.setColumns(20);
        anaResultResult.setFont(new java.awt.Font("微软雅黑", 0, 16)); // NOI18N
        anaResultResult.setRows(5);
        jScrollPane6.setViewportView(anaResultResult);

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel7.setText("分析结果的变化情况");

        waitStr.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel8.setText("请输入需要分析的句子：");

        jButton3.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jButton3.setText("分析");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(filePath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(saveRules, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(execute, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(saveEliminate)
                                .addGap(276, 276, 276)
                                .addComponent(saveExtract)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(judgeLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waitStr, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(0, 51, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judgeResult)
                        .addGap(143, 143, 143))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tablePanel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(230, 230, 230)
                .addComponent(jLabel7)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveRules)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(execute)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(tablePanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveExtract)
                        .addComponent(saveEliminate))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(judgeLabel)
                        .addComponent(judgeResult)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(waitStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(0, 77, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1125, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeActionPerformed
        // TODO add your handling code here:
        anaStackResult.setText("");
        anaStrResult.setText("");
        anaResultResult.setText("");
        waitStr.setText("");
        String input = fileContent.getText().trim();
        String output = "";
        if (!input.equals("")) {
            CommonFunction commfunc = new CommonFunction();
            output = commfunc.eliminateAllLeft(input);
            //用于显示
            output = output.replaceAll("\n", "\r\n");
            eliminateLeft.setText(output);
            output = commfunc.extractAllLeft(input);
            //用于显示
            output = output.replaceAll("\n", "\r\n");
            extractLeft.setText(output);
            TableFunction tablefunc = new TableFunction();
            //显示LL(1)表
            PreProcess pre = new PreProcess(input);
            Set<String> nonTerminalSet = tablefunc.getNonTerminal(pre.getHeadList());
            Set<String> terminalSet = tablefunc.getTerminal(pre.getHeadList(), pre.getBodyList());
            String[] columnNames = new String[terminalSet.size() + 1];
            String[][] rowNames = new String[nonTerminalSet.size()][terminalSet.size() + 1];
            int num = 0;
            columnNames[num] = "LL(1)";
            num++;
            for (String strTmp : terminalSet) {
                columnNames[num] = strTmp;
                num++;
            }
            num = 0;
            for (String strTmp : nonTerminalSet) {
                //填某一行的头
                rowNames[num][0] = strTmp;
                //填某一行的每一列
                for (int i = 1; i < terminalSet.size() + 1; i++) {
                    rowNames[num][i] = tablefunc.getTableRules(tablefunc.buildTableMap(input), strTmp, columnNames[i]);
                }
                //填完后填下一行
                num++;
            }
            JTable jtable = new JTable(rowNames, columnNames);
            tablePanel.setViewportView(jtable);
            if (tablefunc.judgeLL(input) == true) {
                judgeResult.setText("是");
                judgeResult.setForeground(Color.red);
            } else {
                judgeResult.setText("否");
                judgeResult.setForeground(Color.red);
            }
        } else {
            eliminateLeft.setText(output);
            extractLeft.setText(output);
        }
    }//GEN-LAST:event_executeActionPerformed

    private void saveRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRulesActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        int option = jf.showSaveDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {	//假如用户选择了保存
            File file = jf.getSelectedFile();
            String fPath = file.getPath();
            try {
                FileOutputStream fos = new FileOutputStream(file);
                //选择用OutputStreamWriter设置编码方式GBK才能显示ε
                OutputStreamWriter osr = new OutputStreamWriter(fos, "gbk");
                BufferedWriter bw = new BufferedWriter(osr);
                String output = fileContent.getText().trim();
                String []comOutput=output.split("\\r?\\n");
                for(String strTmp:comOutput){
                    bw.write(strTmp);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveRulesActionPerformed

    private void saveExtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveExtractActionPerformed
        // TODO add your handling code here:
         JFileChooser jf = new JFileChooser();
        int option = jf.showSaveDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {	//假如用户选择了保存
            File file = jf.getSelectedFile();
            String fPath = file.getPath();
            try {
                FileOutputStream fos = new FileOutputStream(file);
                //选择用OutputStreamWriter设置编码方式GBK才能显示ε
                OutputStreamWriter osr = new OutputStreamWriter(fos, "gbk");
                BufferedWriter bw = new BufferedWriter(osr);
                String output = extractLeft.getText().trim();
                String []comOutput=output.split("\\r?\\n");
                for(String strTmp:comOutput){
                    bw.write(strTmp);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveExtractActionPerformed

    private void saveEliminateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEliminateActionPerformed
        // TODO add your handling code here:
                 JFileChooser jf = new JFileChooser();
        int option = jf.showSaveDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {	//假如用户选择了保存
            File file = jf.getSelectedFile();
            String fPath = file.getPath();
            try {
                FileOutputStream fos = new FileOutputStream(file);
                //选择用OutputStreamWriter设置编码方式GBK才能显示ε
                OutputStreamWriter osr = new OutputStreamWriter(fos, "gbk");
                BufferedWriter bw = new BufferedWriter(osr);
                String output = eliminateLeft.getText().trim();
                String []comOutput=output.split("\\r?\\n");
                for(String strTmp:comOutput){
                    bw.write(strTmp);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveEliminateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String help = "请按格式输入文法规则：\r\n"
                + "1、各个符号之间请用空格隔开，例如：A a\r\n"
                + "2、一条文法规则的左边与右边请用->隔开，例如：S->A\r\n"
                + "3、每写完一条文法规则请换行\r\n"
                + "4、完整的例子形如：S->A a|B b|stmt A\r\n"
                + "5、需要分析的句子也需要符合上述规则\r\n"
                + "否则无法得到正确结果！！！";
        JOptionPane.showMessageDialog(null, help);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(null);
        File file = jf.getSelectedFile();
        if (file != null) {
            String path = file.getPath();
            filePath.setEditable(false);
            filePath.setText(path);
            BufferedReader reader = null;
            String result = "";
            try {
                FileInputStream fis = new FileInputStream(file);
                //选择用InputStreamReader设置编码方式GBK才能显示ε
                InputStreamReader isr = new InputStreamReader(fis, "gbk");
                reader = new BufferedReader(isr);
                String tempString = null;
                // 一次读入一行，直到读入null为文件结束
                while ((tempString = reader.readLine()) != null) {
                    result += tempString + "\r\n";
                }
                reader.close();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                fileContent.setText(result.trim());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String input = fileContent.getText().trim();
        String output = "";
        if (!input.equals("")) {
            TableFunction tablefunc = new TableFunction();
            tablefunc.analyzeLL(tablefunc.buildTableMap(input), waitStr.getText().trim());
            anaStackResult.setText(tablefunc.getAnaStack());
            anaStrResult.setText(tablefunc.getAnaStr());
            anaResultResult.setText(tablefunc.getAnaResult());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LL1Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LL1Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LL1Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LL1Frame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LL1Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anaResultResult;
    private javax.swing.JTextArea anaStackResult;
    private javax.swing.JTextArea anaStrResult;
    private javax.swing.JTextArea eliminateLeft;
    private javax.swing.JButton execute;
    private javax.swing.JTextArea extractLeft;
    private javax.swing.JTextArea fileContent;
    private javax.swing.JTextField filePath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel judgeLabel;
    private javax.swing.JLabel judgeResult;
    private javax.swing.JButton saveEliminate;
    private javax.swing.JButton saveExtract;
    private javax.swing.JButton saveRules;
    private javax.swing.JScrollPane tablePanel;
    private javax.swing.JTextField waitStr;
    // End of variables declaration//GEN-END:variables
}
